-- In-app notifications (generated by database triggers) and the audit log.
-- Email delivery is not wired yet: it needs an Edge Function with a mail
-- provider secret, which must never reach the Web/Mobile clients.

-- ==========================================================================
-- 1. Notifications
-- ==========================================================================

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  link text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_recipient_idx on public.notifications (recipient_id, created_at desc);
create index notifications_unread_idx on public.notifications (recipient_id) where read_at is null;

alter table public.notifications enable row level security;
revoke all on table public.notifications from anon;
-- Recipients may only mark their notifications as read.
revoke insert, update, delete on table public.notifications from authenticated;
grant update (read_at) on table public.notifications to authenticated;

create policy notifications_select_own on public.notifications for select to authenticated
  using (recipient_id = auth.uid());
create policy notifications_update_own on public.notifications for update to authenticated
  using (recipient_id = auth.uid()) with check (recipient_id = auth.uid());

create function public.notify_permission_holders(
  p_permission text, p_type text, p_title text, p_body text, p_link text
)
returns void
language sql
security definer
set search_path = public, pg_temp
as $$
  insert into public.notifications (recipient_id, type, title, body, link)
  select distinct pr.id, p_type, p_title, p_body, p_link
  from public.profiles pr
  join public.user_roles ur on ur.user_id = pr.id
  join public.role_permissions rp on rp.role_id = ur.role_id
  join public.permissions p on p.id = rp.permission_id
  where p.code = p_permission
    and pr.is_active
    and pr.id is distinct from auth.uid();
$$;

create function public.notify_property_owners(
  p_property_id uuid, p_type text, p_title text, p_body text, p_link text
)
returns void
language sql
security definer
set search_path = public, pg_temp
as $$
  insert into public.notifications (recipient_id, type, title, body, link)
  select distinct o.profile_id, p_type, p_title, p_body, p_link
  from public.property_owners po
  join public.owners o on o.id = po.owner_id
  join public.profiles pr on pr.id = o.profile_id
  where po.property_id = p_property_id
    and pr.is_active
    and o.profile_id is distinct from auth.uid();
$$;

create function public.notify_reservation_events()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_property text;
  v_dates text;
begin
  select name into v_property from public.properties where id = new.property_id;
  v_dates := to_char(new.check_in, 'DD/MM/YYYY') || ' → ' || to_char(new.check_out, 'DD/MM/YYYY');

  if tg_op = 'INSERT' then
    perform public.notify_permission_holders('reservations.manage', 'RESERVATION_CREATED',
      'Nouvelle réservation ' || new.reference, v_property || ' · ' || v_dates, '/app/reservations/' || new.id);
    perform public.notify_property_owners(new.property_id, 'RESERVATION_CREATED',
      'Nouvelle réservation', v_property || ' · ' || v_dates, '/app/reservations/' || new.id);
  elsif new.status is distinct from old.status and new.status = 'CANCELLED' then
    perform public.notify_permission_holders('reservations.manage', 'RESERVATION_CANCELLED',
      'Réservation annulée ' || new.reference, v_property || ' · ' || v_dates, '/app/reservations/' || new.id);
    perform public.notify_property_owners(new.property_id, 'RESERVATION_CANCELLED',
      'Réservation annulée', v_property || ' · ' || v_dates, '/app/reservations/' || new.id);
  elsif new.status is distinct from old.status and new.status in ('CHECK_IN', 'CHECK_OUT') then
    perform public.notify_property_owners(new.property_id, new.status,
      case new.status when 'CHECK_IN' then 'Arrivée du voyageur' else 'Départ du voyageur' end,
      v_property || ' · ' || v_dates, '/app/reservations/' || new.id);
  end if;
  return new;
end;
$$;

create trigger reservations_notify
  after insert or update of status on public.reservations
  for each row
  execute function public.notify_reservation_events();

create function public.notify_task_events()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_property text;
begin
  select name into v_property from public.properties where id = new.property_id;

  if new.assigned_to is not null
     and new.assigned_to is distinct from auth.uid()
     and (tg_op = 'INSERT' or new.assigned_to is distinct from old.assigned_to) then
    insert into public.notifications (recipient_id, type, title, body, link)
    values (new.assigned_to, 'TASK_ASSIGNED',
      case when new.priority = 'URGENT' then 'Tâche urgente : ' else 'Nouvelle tâche : ' end || new.title,
      v_property, '/app/tasks/' || new.id);
  end if;

  if new.priority = 'URGENT' and (tg_op = 'INSERT' or old.priority is distinct from 'URGENT') then
    perform public.notify_permission_holders('tasks.manage', 'TASK_URGENT',
      'Tâche urgente : ' || new.title, v_property, '/app/tasks/' || new.id);
  end if;

  if tg_op = 'UPDATE' and new.status is distinct from old.status and new.status = 'BLOCKED' then
    perform public.notify_permission_holders('tasks.manage', 'TASK_BLOCKED',
      'Tâche bloquée : ' || new.title, v_property, '/app/tasks/' || new.id);
  end if;
  return new;
end;
$$;

create trigger tasks_notify
  after insert or update of assigned_to, priority, status on public.tasks
  for each row
  execute function public.notify_task_events();

create function public.notify_checkin_events()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_reference text;
begin
  if new.status = 'SUBMITTED' and old.status is distinct from 'SUBMITTED' then
    select reference into v_reference from public.reservations where id = new.reservation_id;
    perform public.notify_permission_holders('checkins.manage', 'CHECKIN_SUBMITTED',
      'Check-in à vérifier ' || coalesce(v_reference, ''), coalesce(new.guest_full_name, ''),
      '/app/reservations/' || new.reservation_id);
  end if;
  return new;
end;
$$;

create trigger checkins_notify
  after update of status on public.checkins
  for each row
  execute function public.notify_checkin_events();

create function public.notify_support_events()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_ticket public.support_tickets%rowtype;
begin
  select * into v_ticket from public.support_tickets where id = new.ticket_id;
  if new.author_id = v_ticket.created_by then
    perform public.notify_permission_holders('support.manage', 'SUPPORT_MESSAGE',
      'Support : ' || v_ticket.subject, left(new.body, 140), '/app/support/' || v_ticket.id);
  else
    insert into public.notifications (recipient_id, type, title, body, link)
    values (v_ticket.created_by, 'SUPPORT_REPLY', 'Réponse du support : ' || v_ticket.subject,
            left(new.body, 140), '/app/support/' || v_ticket.id);
  end if;
  return new;
end;
$$;

create trigger support_messages_notify
  after insert on public.support_messages
  for each row
  execute function public.notify_support_events();

create function public.notify_document_events()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.visible_to_owner then
    if new.property_id is not null then
      perform public.notify_property_owners(new.property_id, 'DOCUMENT_SHARED', 'Nouveau document', new.title, '/app/documents');
    elsif new.owner_id is not null then
      insert into public.notifications (recipient_id, type, title, body, link)
      select o.profile_id, 'DOCUMENT_SHARED', 'Nouveau document', new.title, '/app/documents'
      from public.owners o
      where o.id = new.owner_id and o.profile_id is not null;
    end if;
  end if;
  return new;
end;
$$;

create trigger documents_notify
  after insert on public.documents
  for each row
  execute function public.notify_document_events();

-- ==========================================================================
-- 2. Audit log
-- ==========================================================================

create table public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  entity text not null,
  entity_id uuid,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index audit_logs_entity_idx on public.audit_logs (entity, entity_id);
create index audit_logs_created_idx on public.audit_logs (created_at desc);

alter table public.audit_logs enable row level security;
revoke all on table public.audit_logs from anon;
revoke insert, update, delete on table public.audit_logs from authenticated;

create policy audit_logs_select on public.audit_logs for select to authenticated
  using (public.has_permission('audit.view'));

-- Secrets (check-in tokens) are never copied into the log.
create function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_old jsonb;
  v_new jsonb;
begin
  if tg_op in ('UPDATE', 'DELETE') then
    v_old := to_jsonb(old) - 'token' - 'updated_at';
  end if;
  if tg_op in ('INSERT', 'UPDATE') then
    v_new := to_jsonb(new) - 'token' - 'updated_at';
  end if;
  if tg_op = 'UPDATE' and v_old = v_new then
    return null;
  end if;

  insert into public.audit_logs (actor_id, action, entity, entity_id, old_data, new_data)
  values (
    auth.uid(),
    tg_op,
    tg_table_name,
    coalesce(v_new ->> 'id', v_old ->> 'id')::uuid,
    v_old,
    v_new
  );
  return null;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'owners', 'properties', 'property_owners', 'property_listings', 'guests', 'reservations', 'expenses',
    'tasks', 'checkins', 'checkouts', 'documents', 'contract_templates', 'user_roles', 'marketing_campaigns'
  ] loop
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute function public.audit_row_change()',
      table_name || '_audit',
      table_name
    );
  end loop;
end;
$$;

revoke all on function public.notify_permission_holders(text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.notify_property_owners(uuid, text, text, text, text) from public, anon, authenticated;
revoke all on function public.notify_reservation_events() from public, anon, authenticated;
revoke all on function public.notify_task_events() from public, anon, authenticated;
revoke all on function public.notify_checkin_events() from public, anon, authenticated;
revoke all on function public.notify_support_events() from public, anon, authenticated;
revoke all on function public.notify_document_events() from public, anon, authenticated;
revoke all on function public.audit_row_change() from public, anon, authenticated;

-- ==========================================================================
-- 3. Realtime (Supabase creates the supabase_realtime publication)
-- ==========================================================================

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.notifications, public.tasks, public.reservations;
  end if;
end;
$$;
